### PR TITLE
Update/i18n workflow

### PR DESCRIPTION
**Pull request by circlecube**
## Proposed changes

Earlier I assumed the hash was random and unique everytime the make-json command ran. Turns out I was wrong. I didn't dig in to determine what the parameters are for the hash, but tested locally and see that they remain consistent each run (even when i18n strings are added).

This simplifies the workflow and the json files can be updated without needing a rename command (which never worked in github runner).

I'm also removing the commit step since it wasn't working either, and I'm not sure we're quite ready for it anyway. I'm just having the workflow check if there are any file changes and if so failing and echo that the `composer run i18n` script should be run locally to update the files if there are changes, we can disregard for small releases, but should keep it updated as best we can and can look at updating it in the future to run the command and commit the files in a release branch.

This at least brings things to a better place than an i18n step that always fails with no clear direction.

I think once we get to a place where we are ready to update this to a reusable workflow file we can figure out the commit step.

## Type of Change

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

- [ ] I have read the [CONTRIBUTING](https://github.com/bluehost/.github/blob/master/.github/contributing.md) doc
- [ ] Linting and tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by circlecube** [comment]
Also, I should note that I opened this PR against `main` so that the workflow would trigger, but it was branched off `release/2.8.0` so we shouldn't merge it until the release.

**Comment by circlecube** [comment]
✅ i18n workflow passed as expected with no i18n file changes needed.

**Comment by circlecube** [comment]
✅ Command fails as expected with i18n text string edits that are not reflected in the i18n files. I'll revert the string change.

**Comment by circlecube** [comment]
@wpscholar Yes, It was started before the last release. I got it cleaned up merging `main` into this branch.

**Comment by circlecube** [comment]
The module updates in the composer file are just bumping the versions to what is installed and not updating the modules - they've already been updated main, just not bumped in the composer file

**Review by wpscholar — APPROVED** [review]

**Pull request merged**
