### PR TITLE
New UI ecommerce

### PR DESCRIPTION
**Pull request by ramyakrishnai**

### CODE REVIEW

**Comment by ramyakrishnai** [comment]
Hi @circlecube ,  @wpalani  , I've done required changes with the updated version of ecommerce module. kindly review and let me know if any changes required. 

Thank you!!

**Comment by ramyakrishnai** [comment]
found issue in sales && discount page. so, converting back to draft

**Comment by ramyakrishnai** [comment]
have chnaged few colors based on the comments by the hostgator team

attaching the link for your reference.
https://www.figma.com/file/pNcxXb2avx36YAWOD1XkgZ/BH-WP-Hub-Plugin-%7C-Jan---July-2023?type=design&node-id=3867-26686&mode=design&t=hs1tKJkBB5xAZke3-0

**Review by circlecube — APPROVED** [review]
Thanks, this is looking good!

**Pull request merged**
