### PR TITLE
Add newfold-labs/wp-module-notifications

### LINKED ISSUE #39: Add notifications module
Add the notifications module to the plugin.

https://github.com/newfold-labs/wp-module-notifications

### PR DESCRIPTION
**Pull request by aalani95**
Adding the notification module to the plugin (won't be used for now).

Fix #39

### CODE REVIEW

**Comment by wpscholar** [comment]
@aalani95 Since we're using GitFlow, we want to be sure we open our PRs against the `develop` branch. Once I changed the base branch, it looks like there are some Composer file conflicts. Let me know if you need any help addressing these.

**Review by circlecube — DISMISSED** [review]

**Comment by wpscholar** [comment]
@circlecube Isn't there a notifications component that needs to be added to the plugin's React app?

**Comment by circlecube** [comment]
Ah, good memory, yes. @aalani95, check out how we're bringing the component in at:
https://github.com/newfold-labs/wp-plugin-web/blob/main/src/app/index.js#L19
https://github.com/newfold-labs/wp-plugin-web/blob/main/src/app/index.js#L75

**Comment by aalani95** [comment]
> Ah, good memory, yes. @aalani95, check out how we're bringing the component in at: https://github.com/newfold-labs/wp-plugin-web/blob/main/src/app/index.js#L19 https://github.com/newfold-labs/wp-plugin-web/blob/main/src/app/index.js#L75

@circlecube Thanks, I added that code to the app component https://github.com/newfold-labs/wp-plugin-hostgator/pull/46/commits/b343671efa1cdd6985b75c0d6b85e24694d1f4f7

**Review by circlecube — APPROVED** [review]
I made some minor updates to make sure values are set up properly when passing them to the Notifications component.

**Pull request merged**
